version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx ./"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - sphinx

sphinx:
  builder: html
  fail_on_warning: true

# version: 2

# # Set the version of Python and other tools you might need
# build:
#   os: ubuntu-22.04
#   tools:
#     python: "3.13"
#   jobs:
#     pre_build:
#       # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
#       - "jupyter-book config sphinx reports/"

# python:
#    install:
#    - requirements: requirements_jb.txt
# #   - method: pip
# #     path: .

# formats:
#   - pdf
#   - epub